<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php
        echo $this->headTitle('MPRecruiter');

        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

        echo $this->headLink()
            ->prependStylesheet($this->basePath() . '/css/style.css');
        ?>
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,300,600,800,700" rel="stylesheet" type="text/css" />
    </head>
    <body>
        <div class="container">
            <?php echo $this->content; ?>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
