<div id="form">
    <h1>Formulário de registro</h1>
    <div>
        <p>Olá, você está se candidanto para a vaga <strong><?php echo $job->name; ?></strong></p>
        <p><?php echo $job->description; ?></p>
    </div>
    <?php
    $form->prepare();
    $form->setAttribute('action', '/');
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);

    echo '<h2>Informe seus dados para contato:</h2>';
    echo $this->formRow(
        $form->get('name')
    );
    echo $this->formRow(
        $form->get('email')
    );

    echo '<h2>Informe o seu grau de habilidade com os itens a seguir:</h2>';
    foreach ($addFields as $field) {
        echo $this->formRow(
            $form->get('answer_' . $field)
        );
    }

    echo $this->formRow(
        $form->get('submit')
    );
    echo $this->form()->closeTag();
    ?>
</div>
